#!/usr/bin/env python3
"""
regenerate_ioc_index.py — Rebuild threats/iocs/_master-index.yaml from every
actor's iocs.yaml sidecar.

This is intended to run:
  - Nightly via cron/systemd timer
  - After any actor profile update (invoked by the librarian subagent)
  - Manually when debugging ioc-hunt discrepancies

Usage:
    python scripts/regenerate_ioc_index.py [--dry-run]

Behavior:
  - Walks threats/threat-actors/*/iocs.yaml
  - Builds a reverse-lookup dict keyed by indicator value
  - Identifies cross-actor indicators (2+ actors share the same value)
  - Computes stats by type and KEV status
  - Writes threats/iocs/_master-index.yaml (overwrites)
"""

import argparse
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
ACTOR_DIR = REPO_ROOT / "threats" / "threat-actors"
INDEX_PATH = REPO_ROOT / "threats" / "iocs" / "_master-index.yaml"


def collect_indicators() -> tuple[dict, dict]:
    """Walk actor directories, return (lookup_dict, stats)."""
    lookup = defaultdict(lambda: {"actors": [], "details": []})
    stats_by_type = defaultdict(int)
    kev_count = 0
    actors_with_iocs = 0

    for ioc_yaml in sorted(ACTOR_DIR.glob("*/iocs.yaml")):
        try:
            with open(ioc_yaml) as f:
                data = yaml.safe_load(f)
        except Exception as e:
            print(f"  ⚠ failed to parse {ioc_yaml}: {e}", file=sys.stderr)
            continue

        if not data:
            continue

        actor_id = data.get("actor_id")
        if not actor_id:
            continue

        has_indicators = False
        for ind in data.get("indicators", []) or []:
            has_indicators = True
            value = ind.get("value")
            if not value:
                continue
            ind_type = ind.get("type", "unknown")
            stats_by_type[ind_type] += 1

            entry = lookup[str(value)]
            if actor_id not in entry["actors"]:
                entry["actors"].append(actor_id)
            entry["type"] = ind_type
            if ind_type == "cve":
                entry["cvss"] = ind.get("cvss")
                entry["kev"] = ind.get("status") == "kev"
                entry["products"] = [ind.get("product")] if ind.get("product") else []
                if entry.get("kev"):
                    kev_count += 1
            if "role" in ind:
                entry["role"] = ind["role"]
            if "first_seen" in ind:
                entry["first_seen"] = ind["first_seen"]
            if "last_seen" in ind:
                entry["last_seen"] = ind["last_seen"]
            if "malware" in ind:
                entry["malware"] = ind["malware"]
            if "filename" in ind:
                entry["filename"] = ind["filename"]
            if "detection_note" in ind:
                entry["detection_note"] = ind["detection_note"]

        if has_indicators:
            actors_with_iocs += 1

    # Resolve cross-actor indicators
    cross_actor = {v: entry for v, entry in lookup.items() if len(entry["actors"]) > 1}

    stats = {
        "total_indicators": sum(stats_by_type.values()),
        "total_actors_with_iocs": actors_with_iocs,
        "by_type": dict(stats_by_type),
        "cross_actor_indicators": len(cross_actor),
        "kev_count": kev_count,
    }

    # Clean up internal details field
    clean_lookup = {}
    for v, entry in lookup.items():
        clean_lookup[v] = {k: val for k, val in entry.items() if k != "details"}

    return clean_lookup, stats, cross_actor


def write_index(lookup: dict, stats: dict, cross_actor: dict, dry_run: bool) -> None:
    output = {
        "version": 1,
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "generated_by": "scripts/regenerate_ioc_index.py",
        "stats": stats,
        "lookup": lookup,
        "cross_actor": list(cross_actor.keys()),
    }

    dumped = yaml.safe_dump(output, sort_keys=False, default_flow_style=False, width=120)

    if dry_run:
        print("--- DRY RUN — would write to:", INDEX_PATH)
        print(dumped[:2000] + ("\n... [truncated]" if len(dumped) > 2000 else ""))
        return

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(
        "# threats/iocs/_master-index.yaml\n"
        "# GENERATED FILE — regenerated by scripts/regenerate_ioc_index.py\n"
        "# DO NOT HAND-EDIT.\n\n"
        + dumped
    )
    print(f"✅ Wrote {INDEX_PATH}")
    print(f"   {stats['total_indicators']} indicators across {stats['total_actors_with_iocs']} actors")
    print(f"   {stats['cross_actor_indicators']} cross-actor indicators")
    print(f"   {stats['kev_count']} CISA KEV-listed CVEs")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written, don't save")
    args = parser.parse_args()

    print(f"Walking {ACTOR_DIR}...")
    lookup, stats, cross_actor = collect_indicators()
    write_index(lookup, stats, cross_actor, args.dry_run)


if __name__ == "__main__":
    main()
